language: java

services:
  - docker

cache:
  directories:
  - $HOME/.m2

script: 
  - mvn verify checkstyle:check com.github.spotbugs:spotbugs-maven-plugin:check jacoco:check
 
jdk:
  - openjdk11
  - openjdk12
  - openjdk13
