spring:
  datasource:
  #   url: jdbc:postgresql://localhost:5532/agent
  #   username: postgres
  #   password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    contexts: schema-change, initial-data
    liquibase-schema: collection
  jpa:
    open-in-view: false
    properties:
      javax:
        properties:
          validation:
            mode: none
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  # Allow grace timeout period for 20 seconds
  lifecycle.timeout-per-shutdown-phase: 20s
management:
  endpoints:
    web:
      exposure.include: "health,prometheus"
crnk:
  pathPrefix: /api/v1
  domainName: ""
  defaultPageLimit: 20
  maxPageLimit: 1000
  allow-unknown-attributes: true
  # The "include" query-string param is handled by our code and incorporated into the database
  # query, so we don't let Crnk automatically call findOneTarget for each null relation.
  config.lookup.behavior.default: NONE
  jpa.enabled: false
logging:
  level:
    Root: INFO
    # Reduce the logging from the rsql-jpa library, which is otherwise too excessive:
    com.github.tennaito.rsql: ERROR
keycloak:
  enabled: false
  realm: dina
  auth-server-url: http://${KEYCLOAK_HOST_IP}:8080/auth
  ssl-required: none
  resource: agent
  public-client: true
  bearer-only: true
  principal-attribute: preferred_username
  # All endpoints under api require a logged-in user with the "user" role.
  security-constraints:
    - auth-roles:
      - user
      security-collections:
        - patterns:
          - /api/*
javers:
  # Don't let Javers create its tables
  sqlSchemaManagementEnabled: false
  packagesToScan: ca.gc.aafc.collection.api  
# Wait for requests to finish before shutting down:
server.shutdown: graceful
dina.auditing.enabled: true

rabbitmq:
  queue: dina.search.queue
  exchange: dina.search.exchange
  routingkey: dina.search.routingkey
  username: guest
  password: guest
  host: ${RABBITMQ_HOSTNAME:localhost}
  port: 15672
messaging:
  isProducer: false

mybatis:
  mapper-locations: classpath:my-batis/*Mapper.xml
  type-handlers-package: ca.gc.aafc.collection.api.mybatis
