REVOKE CONNECT ON DATABASE collection_test FROM PUBLIC;
REVOKE USAGE, CREATE ON SCHEMA public FROM PUBLIC;

CREATE SCHEMA IF NOT EXISTS collection;
REVOKE CREATE ON SCHEMA collection FROM PUBLIC;

-- migration user
CREATE ROLE migration_user NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'test';
GRANT CONNECT ON DATABASE collection_test TO migration_user;
GRANT USAGE, CREATE ON SCHEMA collection TO migration_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA collection GRANT ALL PRIVILEGES ON TABLES TO migration_user;

-- web user
CREATE ROLE web_user NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'test';
GRANT CONNECT ON DATABASE collection_test TO web_user;
GRANT USAGE ON SCHEMA collection TO web_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA collection TO web_user;
ALTER DEFAULT PRIVILEGES FOR USER migration_user IN SCHEMA collection GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO web_user;
ALTER DEFAULT PRIVILEGES FOR USER migration_user IN SCHEMA collection GRANT SELECT, USAGE ON SEQUENCES TO web_user;

-- By default the PostGIS image will use the public schema so we need to change it
UPDATE pg_extension SET extrelocatable = TRUE WHERE extname = 'postgis';
ALTER EXTENSION postgis SET SCHEMA collection;
