= API

== Additional endpoints

=== material-sample-summary
Get a summary of an existing material sample. The summary includes the https://aafc-bicoe.github.io/dina-documentation/#_effective_determinations[effective determination].

GET `/material-sample-summary/{uuid}`

=== split-configuration

Allows to store split configuration currently used by the ui to customize identifiers.

=== material-sample-identifier-generator

Allows to generate (but not reserve) identifiers for material-sample based on settings.

POST `/material-sample-identifier-generator`

Generate identifiers for a single parent:
```json
{
  "data": {
    "type": "material-sample-identifier-generator",
    "attributes": {
      "currentParentUUID": "parent UUID",
      "quantity": "2",
      "strategy": "DIRECT_PARENT",
      "characterType": "UPPER_LETTER",
      "separator": "DASH"
    }
  }
}
```

Generate identifiers for multiple parents:
```json
{
  "data": {
    "type": "material-sample-identifier-generator",
    "attributes": {
      "currentParentsUUID": ["parent UUID 1", "parent UUID 1"],
      "strategy": "TYPE_BASED",
      "materialSampleType": "CULTURE_STRAIN",
      "characterType": "LOWER_LETTER",
      "separator": "DASH"
    }
  }
}
```

Documentation on strategies can be found in the https://aafc-bicoe.github.io/dina-documentation/#direct-parent-strategy[DINA User Guide]

=== resource-name-identifier
Get the identifier (UUID) based on the name, the type and the group.

GET `/resource-name-identifier?filter[type][EQ]=material-sample&filter[name][EQ]=name1&filter[group][EQ]=aafc`

Available for types :

* collection
* project
* storage-unit
* material-sample
* preparation-type
* preparation-method
* protocol

=== index-refresh
Trigger a message to (re)index a resource.

POST `/index-refresh`

```json
{
  "data": {
    "type": "index-refresh",
    "id": "01939c16-ed4d-7f08-b4d9-bbb825d56cf3",
    "attributes": {
      "docType": "material-sample"
    }
  }
}
```
